AWSTemplateFormatVersion: '2010-09-09'
Description: 'Real estate crawler

  '
Globals:
  Function:
    Timeout: 40
Parameters:
  Table:
    AllowedValues:
    - RealEstate
    Default: RealEstate
    Type: String
Resources:
  Crawler:
    Properties:
      CodeUri: s3://serabalint-crawler-depl/c560c473f6d4669ee07581643eec0cf6
      Environment:
        Variables:
          TABLE:
            Ref: Table
      Events:
        CheckWebsiteScheduledEvent:
          Enabled: false
          Properties:
            Schedule: rate(10 minutes)
          Type: Schedule
      Handler: index.handler
      Policies: AmazonDynamoDBFullAccess
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  DataTableStream:
    Properties:
      BatchSize: 50
      Enabled: true
      EventSourceArn:
        Fn::GetAtt:
        - RealEstateData
        - StreamArn
      FunctionName:
        Fn::GetAtt:
        - DynamoStreamer
        - Arn
      StartingPosition: LATEST
    Type: AWS::Lambda::EventSourceMapping
  DynamoStreamer:
    Properties:
      CodeUri: s3://serabalint-crawler-depl/a2bbb67803c3f3496766cd5d1b634c1a
      Environment:
        Variables:
          TABLE:
            Ref: Table
      Handler: index.handler
      Policies:
      - AmazonDynamoDBFullAccess
      - AmazonSESFullAccess
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  RealEstateData:
    Properties:
      AttributeDefinitions:
      - AttributeName: ID
        AttributeType: S
      KeySchema:
      - AttributeName: ID
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: '5'
        WriteCapacityUnits: '5'
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      TableName:
        Ref: Table
    Type: AWS::DynamoDB::Table
Transform: AWS::Serverless-2016-10-31
