AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Real estate crawler

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 40

Parameters:
  Table:
    Type: String
    Default: real-estates
  AppName:
    Type: String
    Default: real-estate-crawler
    AllowedValues:
    - real-estate-crawler
  Recipients:
    Type: String
    Default: balint.sera+rec@gmail.com
  Environment:
    Type: String
    AllowedValues:
    - stage
    - test
    - prod
    Default: prod


Resources:

  Crawler:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Join [ "-", [ !Ref AppName, "crawler", !Ref Environment ] ]
      CodeUri: crawler/
      Handler: index.handler
      Runtime: nodejs8.10
      Policies: AmazonDynamoDBFullAccess
      Events:
        CheckWebsiteScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(10 minutes)
          Enabled: False
      Environment:
        Variables:
          TABLE: !Join [ "-", [ !Ref AppName, !Ref Table, !Ref Environment ] ]

  RealEstateData:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: "ID"
        AttributeType: "S"
      KeySchema:
      - AttributeName: "ID"
        KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: !Join [ "-", [ !Ref AppName, !Ref Table, !Ref Environment ] ]
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  DynamoStreamer:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join [ "-", [ !Ref AppName, "alert", !Ref Environment ] ]
      CodeUri: dynamo_streamer/
      Handler: index.handler
      Runtime: nodejs8.10
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonSESFullAccess
      Environment:
        Variables:
          TABLE: !Join [ "-", [ !Ref AppName, !Ref Table, !Ref Environment ] ]
          RECIPIENTS: !Ref Recipients

  DataTableStream:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 50
      Enabled: True
      EventSourceArn:
        Fn::GetAtt: [ RealEstateData , StreamArn ]
      FunctionName:
        Fn::GetAtt: [ DynamoStreamer , Arn ]
      StartingPosition: LATEST #always start at the tail of the stream